---
- name: Installing the WLAN driver for the RTL8192E
  hosts: all

  tasks:
    - name: "Update the repositories and upgrade them (apt-get update + apt-get upgrade)"
      shell: sudo apt-get update && sudo apt-get upgrade -y

    - name: "Install git to clone the repositories"
      become: yes
      apt:
        name: git
        state: present

    - name: "Install the Raspberry Pi Kernel Header"
      become: yes
      apt:
        name:  raspberrypi-kernel-headers
        state: present

    - name: "Clone the AWX APM repository"
      git:
        repo: https://github.com/fankp1/WLAN-Driver-Kunbus-Proxy-.git
        dest: /home/pi/wlan_driver
        clone: yes
